package dev.karmakrafts.rakii

/**
 * A marker annotation for APIs in the RAkII resource management system that are
 * intended to be generated or transformed by the compiler plugin.
 * 
 * This annotation marks functions and properties that are typically generated or
 * modified by the RAkII compiler plugin during compilation. Direct use of these
 * APIs by developers is discouraged unless the containing class is explicitly
 * marked with the [SkipDropTransforms] annotation to opt out of automatic
 * transformations.
 * 
 * When a class is marked with [SkipDropTransforms], the developer takes responsibility
 * for implementing the proper resource management logic that would otherwise be
 * generated by the compiler plugin.
 * 
 * This annotation helps prevent accidental misuse of internal APIs that are part of
 * RAkII's code generation system, ensuring that resource management remains consistent
 * and reliable.
 */
@RequiresOptIn("The API you're trying to use shouldn't be used without @SkipDropTransforms")
@Retention(AnnotationRetention.BINARY)
annotation class GeneratedDropApi
