package dev.karmakrafts.rakii

@RequiresOptIn("The API you're trying to use shouldn't be used directly as it is generated by RAkII")
@Retention(AnnotationRetention.BINARY)
annotation class GeneratedDropApi